# Generated by Django 6.0.7 on 2026-07-10 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="subscribe",
            name="course",
            field=models.ForeignKey(
                help_text="Подписка на курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subs_course",
                to="lms.course",
                verbose_name="Курс подписки",
            ),
        ),
        migrations.AddField(
            model_name="subscribe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subs_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
